// The database enums, as string unions (formerly generated by Prisma).
export type UnitType = 'LITER' | 'KG' | 'BOTTLE';
export type BottleSize = 'QUARTER' | 'HALF' | 'ONE';
export type PaymentMethod = 'CASH' | 'CHEQUE' | 'CREDIT';
export type PaymentKind = 'SETTLEMENT' | 'LOAN';
export type PaymentDirection = 'RECEIVED' | 'PAID';
export type PurchaseMaterial = 'COPRA' | 'CHARCOAL' | 'OTHER';
export type CashEntryType = 'OPENING_FLOAT' | 'TOP_UP' | 'EXPENSE';
export type AuditAction = 'CREATE' | 'DELETE' | 'UPDATE';
export type AuditEntity =
  | 'SALE'
  | 'PURCHASE'
  | 'CASH_ENTRY'
  | 'ADMIN_SETTINGS'
  | 'DEVICE'
  | 'CUSTOMER'
  | 'CUSTOMER_PAYMENT'
  | 'CHARCOAL_ADJUSTMENT'
  | 'TEMP_ACCESS'
  | 'CREDENTIAL'
  | 'PRICE';
export type ActorType = 'COUNTER' | 'ADMIN' | 'SYSTEM';
export type PinRole = 'USER' | 'ADMIN';
